export interface FakerOption {
    label: string;
    value: string;
  }
  
  export const stringFakerOptions: FakerOption[] = [
    { label: "First Name", value: "person.firstName" },
    { label: "Last Name", value: "person.lastName" },
    { label: "Full Name", value: "person.fullName" },
    { label: "Email", value: "internet.email" },
    { label: "Phone", value: "phone.number" },
    { label: "Username", value: "internet.username" },
    { label: "Password", value: "internet.password" },
    { label: "Street Address", value: "location.streetAddress" },
    { label: "City", value: "location.city" },
    { label: "Country", value: "location.country" },
    { label: "Zip Code", value: "location.zipCode" },
    { label: "State", value: "location.state" },
    { label: "Company Name", value: "company.name" },
    { label: "Job Title", value: "person.jobTitle" },
    { label: "Department", value: "commerce.department" },
    { label: "Product Name", value: "commerce.productName" },
    { label: "Price", value: "commerce.price" },
    { label: "UUID", value: "string.uuid" },
    { label: "URL", value: "internet.url" },
    { label: "IP Address", value: "internet.ip" },
    { label: "Lorem Word", value: "lorem.word" },
    { label: "Lorem Sentence", value: "lorem.sentence" },
    { label: "Lorem Paragraph", value: "lorem.paragraph" },
    { label: "Color", value: "color.human" },
    { label: "Date (Past)", value: "date.past" },
    { label: "Date (Future)", value: "date.future" },
    { label: "Date (Recent)", value: "date.recent" },
    { label: "File Name", value: "system.fileName" },
    { label: "Mime Type", value: "system.mimeType" },
    { label: "User Agent", value: "internet.userAgent" },
    { label: "Word", value: "word.sample" },
  ];
  
  export const numberFakerOptions: FakerOption[] = [
    { label: "Random Int", value: "number.int" },
    { label: "Random Float", value: "number.float" },
    { label: "Age (1-18)", value: "custom.ageChild" },
    { label: "Age (18-65)", value: "custom.ageAdult" },
    { label: "Age (1-100)", value: "custom.ageFull" },
    { label: "Rating (1-5)", value: "custom.rating" },
    { label: "Rating (1-10)", value: "custom.ratingTen" },
    { label: "Percentage (0-100)", value: "custom.percentage" },
    { label: "Discount (5-50%)", value: "custom.discount" },
    { label: "Score (0-100)", value: "custom.scoreHundred" },
    { label: "Score (0-1000)", value: "custom.score" },
    { label: "Quantity (1-10)", value: "custom.quantitySmall" },
    { label: "Quantity (1-100)", value: "custom.quantity" },
    { label: "Quantity (1-1000)", value: "custom.quantityLarge" },
    { label: "Price ($1-$999)", value: "custom.price" },
    { label: "Salary ($30k-$150k)", value: "custom.salary" },
    { label: "Order ID", value: "custom.orderId" },
    { label: "User ID", value: "custom.userId" },
    { label: "Serial Number", value: "custom.serialNumber" },
    { label: "Year (1990-2030)", value: "custom.year" },
    { label: "Month (1-12)", value: "custom.month" },
    { label: "Day (1-31)", value: "custom.day" },
    { label: "Hour (0-23)", value: "custom.hour" },
    { label: "Minute (0-59)", value: "custom.minute" },
    { label: "HTTP Status Code", value: "custom.httpStatus" },
    { label: "Port (1-65535)", value: "custom.port" },
    { label: "Page Number (1-500)", value: "custom.pageNumber" },
    { label: "Index (0-99)", value: "custom.index" },
    { label: "Byte (0-255)", value: "custom.byte" },
    { label: "Binary (0 or 1)", value: "custom.binary" },
    { label: "Height cm (140-200)", value: "custom.heightCm" },
    { label: "Weight kg (40-120)", value: "custom.weightKg" },
    { label: "Temperature °C (-10 to 40)", value: "custom.temperature" },
    { label: "Latitude", value: "custom.latitude" },
    { label: "Longitude", value: "custom.longitude" },
    { label: "Stock Price", value: "custom.stockPrice" },
    { label: "Employee Count (1-500)", value: "custom.employeeCount" },
  ];
  
  export const arrayItemTypes = [
    { label: "String", value: "string" },
    { label: "Number", value: "number" },
    { label: "Boolean", value: "boolean" },
    { label: "Object", value: "object" },
  ];